backend:
  name: github
  repo: nilesh5995/nilesh5995.github.io
  branch: live
  site_domain: awesome-bhabha-91d705.netlify.com
  show_preview_links: true
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img

collections:

  - name: "Pages"
    label: "pages"
    create: true
    publish_mode: editorial_workflow
    widget: list
    files:
      - file: "src/pages/team/peter-van-eijk.md"
        label: "Team  Page"
        name: "Team"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index.js"}
          - {label: "Path", name: "path", widget: "string"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Date", name: "date", widget: "datetime"}
          - {label: "Draft", name: "draft", widget: "boolean"}
          - {label: "Image", name: "image", widget: image}
          - {label: "jobtitle", name: "jobtitle", widget: "string"}
          - {label: "Linkedin", name: "linkedinurl", widget: "string"}
          - {label: "weight", name: "weight", widget: "number"}
          - {label: "html", name: "html", widget: "markdown"}
